In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

等差序列生成方式：


In [5]:
# np.linspace(开始，结束（包含），个数）
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [4]:
# np.arange(开始，结束（不包含），步长）
np.arange(1,8,2)

array([1, 3, 5, 7])

矩阵


In [6]:
# zeros矩阵，矩阵里填充0
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# eye矩阵，从左到右对角线为1(true)
# eye(i) 等行等列的方阵
# eye(i,j) i行，j列矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# eye设置偏移对角线
# eye(i,j,k=x) k偏移量只能传正数，向右偏移
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [12]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.eye(2,3)


array([[1., 0., 0.],
       [0., 1., 0.]])

In [14]:
# full矩阵，赋值矩阵
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [18]:
# 每行填入相同的值，不能多于列数的值
np.full((2,3),[1,2,3])

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [19]:
# 随机矩阵
np.random.rand(3) #生成0-1三个随机列表

array([0.35266472, 0.86135779, 0.66733703])

In [20]:
# 生成2行3列个0-1随机数
np.random.rand(2,3)

array([[0.69396814, 0.00978102, 0.71642443],
       [0.92135013, 0.92178916, 0.86283654]])

In [21]:
# 生成一个区间内的随机数
np.random.uniform(5,15,3)

array([12.05481098, 10.24527189,  5.49394712])

In [22]:
# 生成N(0,1)标准正态分布
np.random.randn(3)

array([-0.22480656, -0.32525123,  0.68554669])

In [23]:
np.random.randn(2,2)

array([[ 0.87702354, -0.97907573],
       [ 0.46252875, -1.53104983]])

In [24]:
# 服从方差x均值u的一元正态分布
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma

array([4.34616891, 4.21573399, 2.55231659])

In [25]:
# 上一格的简化函数 normal 方差均值的正态分布
np.random.normal(3, 2.5, 3) # 均值，方差，队列长度

array([4.200134  , 7.65765138, 2.40028285])

In [26]:
# randint 生成随机整数的最小值，最大值（不包）和维度大小
np.random.randint(5,15,4) # 最小值，最大值，个数

array([ 9,  8, 10,  7])

In [27]:
# 通过一定概率抽取列表
my_list = list('abcde')
np.random.choice(my_list,3)

array(['c', 'e', 'e'], dtype='<U1')

In [33]:
# p 为概率， replace:false 不重复
np.random.choice(my_list, 3, replace=False, p=[0.1,0.1,0.3,0.2,0.3])


array(['c', 'e', 'a'], dtype='<U1')

In [34]:
# 打散原列表
np.random.permutation(my_list)

array(['c', 'e', 'b', 'a', 'd'], dtype='<U1')

In [35]:
# 固定随机数的输出结果
np.random.rand()

0.6097167332304061

In [36]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [37]:
np.random.rand()

0.7151893663724195

In [38]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

数组的变型

In [45]:
# 倒置
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
# 维度变换 reshape
np.array(list('abcdef')).reshape(2,3)

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [47]:
np.array(list('abcdef')).reshape((2,3),order='C') # C按行

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [48]:
np.array(list('abcdef')).reshape((2,3),order='F') # F按列

array([['a', 'c', 'e'],
       ['b', 'd', 'f']], dtype='<U1')

In [49]:
# -1 是自动计算
np.array(list('abcdef')).reshape(3,-1)


array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')